# golangci-lint configuration for go-agent
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Essential linters
    - errcheck        # Check for unchecked errors
    - staticcheck     # Advanced static analysis
    - gosimple        # Simplify code
    - govet           # Go vet
    - unused          # Unused constants, variables, functions, and types

    # Code quality
    - gocyclo         # Cyclomatic complexity
    - gocritic        # Code criticism
    - gofmt           # Format checker
    - goimports       # Import organization
    - misspell        # Misspellings
    - ineffassign     # Ineffectual assignments
    - unconvert       # Unnecessary type conversions

    # Best practices
    - contextcheck    # Check context usage
    - bodyclose       # Check HTTP response body closed
    - noctx           # HTTP requests without context
    - errname         # Error naming conventions
    - errorlint       # Error wrapping
    # exportloopref is deprecated since Go 1.22 (loopvar) - replaced by copyloopvar

    # Style
    - revive          # Comprehensive linting
    - stylecheck      # Style checks

  disable:
    - typecheck       # Can cause issues with generated code

linters-settings:
  gocyclo:
    min-complexity: 15

  govet:
    enable-all: true
    disable:
      - shadow        # Allow variable shadowing

  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close

  staticcheck:
    checks: ["all"]

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: package-comments
        disabled: true    # Allow packages without comments in tests
      - name: unexported-return
        disabled: true

  stylecheck:
    checks: ["all"]
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega

  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - badCond
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - caseOrder
      - commentFormatting
      - commentedOutCode
      - defaultCaseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - flagDeref
      - flagName
      - hexLiteral
      - ifElseChain
      - importShadow
      - indexAlloc
      - initClause
      - methodExprCall
      - nilValReturn
      - octalLiteral
      - offBy1
      - rangeExprCopy
      - rangeValCopy
      - regexpMust
      - sloppyLen
      - stringXbytes
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlambda
      - unnecessaryBlock
      - unslice
      - valSwap
      - weakCond
      - wrapperFunc
      - yodaStyleExpr

issues:
  exclude-dirs:
    - vendor
    - bin
    - examples        # Exclude examples from linting
    - tests/testdata  # Exclude generated protobuf code

  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocyclo
        - dupl
        - gocritic

    # Allow dot imports in tests
    - path: _test\.go
      text: "dot imports"
      linters:
        - stylecheck

    # Allow long functions in integration tests
    - path: tests/integration/
      linters:
        - funlen
        - gocyclo

    # Exclude generated code
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Exclude generated gateway code
    - path: ".*\\.pb\\.gw\\.go"
      linters:
        - all

    # Allow G114 (Use of net/http serve function with no timeout) in examples and tests
    - path: (examples|tests)/
      text: "G114:"
      linters:
        - gosec

    # Allow G402 (TLS InsecureSkipVerify) in tests
    - path: tests/
      text: "G402:"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
